name: Python Code Formatter

on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # You can change this to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run Black to auto-format the code
        run: |
          black .

      - name: Commit and push the formatted code
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add .
          git commit -m "Auto-format code with Black" || echo "No changes to commit"
          git push

